# Generated by Django 3.2.7 on 2021-10-30 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaldeclaration',
            name='other_symptoms',
            field=models.TextField(blank=True, null=True),
        ),
    ]
