# Generated by Django 3.2.7 on 2021-10-30 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('form', '0002_medicaldeclaration_other_symptoms'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_x_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='test',
            name='result',
            field=models.CharField(choices=[('NONE', 'None'), ('NEGATIVE', 'Negative'), ('POSITIVE', 'Positive')], default='NONE', max_length=16),
        ),
    ]
