# Generated by Django 3.2.7 on 2021-10-30 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_auto_20211031_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='code',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
