# Generated by Django 3.2.7 on 2021-11-02 13:33

from django.db import migrations
from ..models import test_code_generator

def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Test = apps.get_model("form", "Test")
    db_alias = schema_editor.connection.alias
    tests = Test.objects.using(db_alias).all()
    for test in tests:
        test.code = test_code_generator()
        test.save()

def reverse_func(apps, schema_editor):
    ...

class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_alter_test_code'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
