# Generated by Django 3.2.7 on 2021-11-02 13:40

from django.db import migrations, models
import form.models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_auto_20211102_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='code',
            field=models.CharField(default=form.models.test_code_generator, max_length=32, unique=True),
        ),
    ]
