# Generated by Django 3.2.7 on 2022-01-02 17:22

from django.db import migrations
from utils.enums import HealthDeclarationConclude

def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    MedicalDeclaration = apps.get_model("form", "MedicalDeclaration")
    db_alias = schema_editor.connection.alias
    declarations = MedicalDeclaration.objects.using(db_alias).all()

    for item in declarations:
        item.conclude = HealthDeclarationConclude.NORMAL

        if item.extra_symptoms and item.extra_symptoms != '':
            item.conclude = HealthDeclarationConclude.UNWELL
        if item.main_symptoms and item.main_symptoms != '':
            item.conclude = HealthDeclarationConclude.SERIOUS
        
        item.save()

def reverse_func(apps, schema_editor):
    ...

class Migration(migrations.Migration):

    dependencies = [
        ('form', '0007_medicaldeclaration_conclude'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
