# Generated by Django 3.2.7 on 2022-01-02 18:11

from random import randint
from django.db import migrations

def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    MedicalDeclaration = apps.get_model("form", "MedicalDeclaration")
    db_alias = schema_editor.connection.alias
    declarations = MedicalDeclaration.objects.using(db_alias).all()

    for item in declarations:
        user_code = item.user.code
        first_part = ('0000000000' + str(user_code))[-3:]
        second_and_third_part = ''.join(str(randint(0, 9)) for i in range(12))
        item.code = first_part + second_and_third_part
        item.save()

def reverse_func(apps, schema_editor):
    ...

class Migration(migrations.Migration):

    dependencies = [
        ('form', '0009_medicaldeclaration_code'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
