# Generated by Django 3.2.7 on 2022-01-02 18:33

from django.db import migrations, models
import form.models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0010_auto_20220103_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaldeclaration',
            name='code',
            field=models.CharField(default=form.models.medical_declaration_code_generator, max_length=32, unique=True),
        ),
    ]
