# Generated by Django 3.2.7 on 2022-05-13 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0015_pandemic_day_between_tests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicaldeclaration',
            name='blood_pressure',
        ),
    ]
