# Generated by Django 3.2.7 on 2022-05-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0016_remove_medicaldeclaration_blood_pressure'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaldeclaration',
            name='blood_pressure_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicaldeclaration',
            name='blood_pressure_min',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
