# Generated by Django 3.2.7 on 2021-10-20 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quarantine_ward', '0002_initial'),
        ('user_account', '0002_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(choices=[('F0', 'F0'), ('F1', 'F1'), ('F2', 'F2'), ('F3', 'F3')], default='F0', max_length=8)),
                ('quarantined_place_before', models.CharField(blank=True, max_length=128, null=True)),
                ('positive_tested_before', models.BooleanField(default=False)),
                ('abroad', models.BooleanField(default=False)),
                ('quarantined_at', models.DateTimeField(blank=True, null=True)),
                ('quarantined_status', models.CharField(choices=[('COMPLETED', 'Completed'), ('QUARANTINING', 'Quarantining'), ('REQUARANTINING', 'Requarantining'), ('MOVED', 'Moved')], default='QUARANTINING', max_length=32)),
                ('last_tested', models.DateTimeField(blank=True, null=True)),
                ('health_status', models.CharField(choices=[('NORMAL', 'Normal'), ('UNWELL', 'Unwell'), ('SERIOUS', 'Serious')], default='NORMAL', max_length=32)),
                ('health_note', models.TextField(blank=True, null=True)),
                ('positive_test', models.BooleanField(default=False)),
                ('background_disease', models.CharField(choices=[('NONE', 'None'), ('TIEU_DUONG', 'Tieu Duong'), ('UNG_THU', 'Ung Thu'), ('HEN_SUYEN', 'Hen Suyen'), ('CAO_HUYET_AP', 'Cao Huyet Ap'), ('BENH_GAN', 'Benh Gan'), ('BENH_THAN_MAN_TINH', 'Benh Than Man Tinh'), ('BENH_TIM_MACH', 'Benh Tim Mach'), ('BENH_LY_MACH_MAU_NAO', 'Benh Ly Mach Mau Nao'), ('OTHER', 'Other')], default='NONE', max_length=64)),
                ('background_disease_note', models.TextField(blank=True, null=True)),
                ('care_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_x_care_staff', to=settings.AUTH_USER_MODEL)),
                ('custom_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_x_custom_user', to=settings.AUTH_USER_MODEL)),
                ('quarantine_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_x_quarantine_room', to='quarantine_ward.quarantineroom')),
            ],
        ),
    ]
