# Generated by Django 3.2.7 on 2021-10-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0003_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='background_disease',
            field=models.TextField(blank=True, null=True),
        ),
    ]
