# Generated by Django 3.2.7 on 2021-10-23 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0007_auto_20211023_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='address',
            new_name='detail_address',
        ),
        migrations.RemoveField(
            model_name='member',
            name='quarantined_place_before',
        ),
    ]
