# Generated by Django 3.2.7 on 2021-10-23 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0008_auto_20211024_0052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='quanrantine_ward',
            new_name='quarantine_ward',
        ),
    ]
