# Generated by Django 3.2.7 on 2021-10-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0009_rename_quanrantine_ward_customuser_quarantine_ward'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='verified',
            new_name='email_verified',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Waiting'), ('LOCKED', 'Locked'), ('AVAILABLE', 'Available')], default='AVAILABLE', max_length=32),
        ),
    ]
