# Generated by Django 3.2.7 on 2021-11-01 18:06

from django.db import migrations
from ..models import user_code_generator


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    CustomUser = apps.get_model("user_account", "CustomUser")
    db_alias = schema_editor.connection.alias
    users = CustomUser.objects.using(db_alias).all()
    for user in users:
        user.code = user_code_generator()
        user.save()

def reverse_func(apps, schema_editor):
    ...

class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0011_customuser_code'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
