# Generated by Django 3.2.7 on 2021-11-01 18:18

from django.db import migrations, models
import user_account.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0012_auto_20211102_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='code',
            field=models.CharField(default=user_account.models.user_code_generator, max_length=18, unique=True),
        ),
    ]
