# Generated by Django 3.2.7 on 2021-11-03 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0013_alter_customuser_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='staff',
        ),
    ]
