# Generated by Django 3.2.7 on 2021-11-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0014_auto_20211103_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Waiting'), ('REFUSED', 'Refused'), ('LOCKED', 'Locked'), ('AVAILABLE', 'Available')], default='AVAILABLE', max_length=32),
        ),
    ]
