# Generated by Django 3.2.7 on 2021-11-14 08:17

from django.db import migrations

def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    CustomUser = apps.get_model("user_account", "CustomUser")
    db_alias = schema_editor.connection.alias
    users = CustomUser.objects.using(db_alias).all()

    for user in users:
        if user.email == '':
            user.email = None
        else:
            if user.email != None:
                test_users = CustomUser.objects.using(db_alias).filter(email=user.email)
                if len(test_users) >= 2:
                    user.email = None

        if user.health_insurance_number == '':
            user.health_insurance_number = None
        else:
            if user.health_insurance_number != None:
                test_users = CustomUser.objects.using(db_alias).filter(health_insurance_number=user.health_insurance_number)
                if len(test_users) >= 2:
                    user.health_insurance_number = None

        if user.identity_number == '':
            user.identity_number = None
        else:
            if user.identity_number != None:
                test_users = CustomUser.objects.using(db_alias).filter(identity_number=user.identity_number)
                if len(test_users) >= 2:
                    user.identity_number = None

        if user.passport_number == '':
            user.passport_number = None
        else:
            if user.passport_number != None:
                test_users = CustomUser.objects.using(db_alias).filter(passport_number=user.passport_number)
                if len(test_users) >= 2:
                    user.passport_number = None
        
        user.save()

def reverse_func(apps, schema_editor):
    ...

class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0015_alter_customuser_status'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
