# Generated by Django 3.2.7 on 2021-11-14 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0017_auto_20211114_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='positive_test',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
