# Generated by Django 3.2.7 on 2021-11-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0018_alter_member_positive_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='quarantined_finished_at',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
