# Generated by Django 3.2.7 on 2021-11-15 17:31

from django.db import migrations

def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    CustomUser = apps.get_model("user_account", "CustomUser")
    db_alias = schema_editor.connection.alias
    users = CustomUser.objects.using(db_alias).all()

    for user in users:
        if user.ward != None:
            user.district = user.ward.district
        if user.district != None:
            user.city = user.district.city
        if user.city != None:
            user.country = user.city.country
        
        user.save()

def reverse_func(apps, schema_editor):
    ...

class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0019_member_quarantined_finished_at'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
