# Generated by Django 3.2.7 on 2021-12-30 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0020_auto_20211116_0031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_tested', models.DateTimeField(blank=True, null=True)),
                ('health_status', models.CharField(choices=[('NORMAL', 'Normal'), ('UNWELL', 'Unwell'), ('SERIOUS', 'Serious')], default='NORMAL', max_length=32)),
                ('health_note', models.TextField(blank=True, null=True)),
                ('positive_test_now', models.BooleanField(blank=True, null=True)),
                ('care_area', models.TextField(blank=True, null=True)),
                ('custom_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_x_custom_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_tested', models.DateTimeField(blank=True, null=True)),
                ('health_status', models.CharField(choices=[('NORMAL', 'Normal'), ('UNWELL', 'Unwell'), ('SERIOUS', 'Serious')], default='NORMAL', max_length=32)),
                ('health_note', models.TextField(blank=True, null=True)),
                ('positive_test_now', models.BooleanField(blank=True, null=True)),
                ('custom_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager_x_custom_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
