# Generated by Django 3.2.7 on 2021-12-30 17:52

from django.db import migrations

def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    CustomUser = apps.get_model("user_account", "CustomUser")
    Manager = apps.get_model("user_account", "Manager")
    Staff = apps.get_model("user_account", "Staff")
    db_alias = schema_editor.connection.alias
    users = CustomUser.objects.using(db_alias).all()

    for user in users:
        if user.role.name == 'SUPER_MANAGER' or user.role.name == 'MANAGER':
            manager = Manager(custom_user=user)
            manager.save()
            if hasattr(user, 'member_x_custom_user'):
                member = user.member_x_custom_user
                member.delete()
        elif user.role.name == 'STAFF':
            staff = Staff(custom_user=user)
            staff.save()
            if hasattr(user, 'member_x_custom_user'):
                member = user.member_x_custom_user
                member.delete()

def reverse_func(apps, schema_editor):
    ...

class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0021_manager_staff'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
