# Generated by Django 3.2.7 on 2022-01-03 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0022_auto_20211231_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='last_tested_had_result',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='last_tested_had_result',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='last_tested_had_result',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
