# Generated by Django 3.2.7 on 2022-01-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0024_auto_20220103_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='new_quarantined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='new_quarantined_finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
