# Generated by Django 3.2.7 on 2022-01-05 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0026_auto_20220105_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='quarantined_at',
        ),
        migrations.RemoveField(
            model_name='member',
            name='quarantined_finished_at',
        ),
    ]
