# Generated by Django 3.2.7 on 2022-01-05 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0027_auto_20220106_0026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='new_quarantined_at',
            new_name='quarantined_at',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='new_quarantined_finished_at',
            new_name='quarantined_finished_at',
        ),
    ]
