# Generated by Django 3.2.7 on 2022-01-15 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0030_alter_member_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='abroad',
        ),
    ]
