# Generated by Django 3.2.7 on 2022-01-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0032_auto_20220119_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='number_of_vaccine_doses',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name='member',
            name='number_of_vaccine_doses',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name='staff',
            name='number_of_vaccine_doses',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
        ),
    ]
