# Generated by Django 3.2.7 on 2022-01-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0033_auto_20220128_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Waiting'), ('REFUSED', 'Refused'), ('LOCKED', 'Locked'), ('AVAILABLE', 'Available'), ('LEAVE', 'Leave')], default='AVAILABLE', max_length=32),
        ),
    ]
