# Generated by Django 3.2.7 on 2022-02-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0035_auto_20220131_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='quarantined_status',
            field=models.CharField(choices=[('COMPLETED', 'Completed'), ('QUARANTINING', 'Quarantining'), ('REQUARANTINING', 'Requarantining'), ('HOSPITALIZE', 'Hospitalize'), ('MOVED', 'Moved')], default='QUARANTINING', max_length=32),
        ),
    ]
