# Generated by Django 3.2.7 on 2022-04-06 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quarantine_ward', '0005_quarantineward_pandemic'),
        ('form', '0014_auto_20220312_0136'),
        ('user_account', '0041_destinationhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuarantineHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ENDED', 'Ended')], default='PRESENT', max_length=32)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('end_type', models.CharField(blank=True, choices=[('HOSPITALIZE', 'Hospitalize'), ('COMPLETED', 'Completed'), ('CHANGE_ROOM', 'Change Room')], max_length=32, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quarantine_history_x_created_by', to=settings.AUTH_USER_MODEL)),
                ('pandemic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quarantine_history_x_pandemic', to='form.pandemic')),
                ('quarantine_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quarantine_history_x_quarantine_room', to='quarantine_ward.quarantineroom')),
                ('quarantine_ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quarantine_history_x_quanrantine_ward', to='quarantine_ward.quarantineward')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quarantine_history_x_updated_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarantine_history_x_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
