# Generated by Django 3.2.7 on 2022-04-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0044_auto_20220408_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='quarantined_status',
            field=models.CharField(choices=[('COMPLETED', 'Completed'), ('QUARANTINING', 'Quarantining'), ('HOSPITALIZE', 'Hospitalize'), ('MOVED', 'Moved')], default='QUARANTINING', max_length=32),
        ),
    ]
