# Generated by Django 3.2.7 on 2022-04-25 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0045_alter_member_quarantined_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='professional',
            field=models.CharField(blank=True, choices=[('Viên chức / Nhân viên', 'Vien Chuc'), ('Công chức', 'Cong Chuc'), ('Công nhân', 'Cong Nhan'), ('Buôn bán / Kinh doanh', 'Kinh Doanh'), ('Doanh nghiệp / Sale', 'Doanh Nghiep'), ('Lao động tự do', 'Lao Dong'), ('Hưu trí', 'Huu Tri'), ('Kế toán', 'Ke Toan'), ('Nhân viên văn phòng', 'Nhan Vien Van Phong'), ('Công an', 'Cong An'), ('Làm nông', 'Lam Nong'), ('Sinh viên', 'Sinh Vien'), ('Phóng viên', 'Phong Vien'), ('Lái xe', 'Lai Xe'), ('Luật sư', 'Luat Su'), ('Kỹ sư', 'Ky Su'), ('Nhân viên y tế', 'Nhan Vien Y Te'), ('Nghệ sĩ / KOLs', 'Nghe Si')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='first_positive_test_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='quarantine_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
