# Generated by Django 3.2.7 on 2021-10-17 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
        ('quarantine_ward', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quarantineward',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quarantine_ward_x_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quarantineward',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quarantine_ward_x_district', to='address.district'),
        ),
        migrations.AddField(
            model_name='quarantineward',
            name='main_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quarantine_ward_x_main_manager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quarantineward',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quarantine_ward_x_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quarantineward',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quarantine_ward_x_ward', to='address.ward'),
        ),
        migrations.AddField(
            model_name='quarantineroom',
            name='quarantine_floor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarantine_room_x_quarantine_floor', to='quarantine_ward.quarantinefloor'),
        ),
        migrations.AddField(
            model_name='quarantinefloor',
            name='quarantine_building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarantine_floor_x_quarantine_building', to='quarantine_ward.quarantinebuilding'),
        ),
        migrations.AddField(
            model_name='quarantinebuilding',
            name='quarantine_ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarantine_building_x_quarantine_ward', to='quarantine_ward.quarantineward'),
        ),
    ]
