# Generated by Django 3.2.7 on 2021-11-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quarantine_ward', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarantineward',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
    ]
