# Generated by Django 3.2.7 on 2022-04-24 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quarantine_ward', '0005_quarantineward_pandemic'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quarantinebuilding',
            unique_together={('name', 'quarantine_ward')},
        ),
        migrations.AlterUniqueTogether(
            name='quarantinefloor',
            unique_together={('name', 'quarantine_building')},
        ),
        migrations.AlterUniqueTogether(
            name='quarantineroom',
            unique_together={('name', 'quarantine_floor')},
        ),
    ]
