# Generated by Django 3.2.7 on 2022-03-02 16:45

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        UnaccentExtension()
    ]
